Domain = "localhost"
Port = 8080
EnableSSL = false
LogLevel = "INFO" # Options: CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
DataDir = "data" # Relative to jabawiki dir
CookieSecret = "secretchangeme!"
